const express=require('express'),http=require('http'),path=require('path'),axios=require('axios');
const {Server}=require('socket.io'); const {io:clientIO}=require('socket.io-client');
const app=express(),server=http.createServer(app),io=new Server(server); app.use(express.static(path.join(__dirname,'public')));
const store=new Map(); const CFG=[{h:15,c:1,label:'15M → 1M'},{h:30,c:1,label:'30M → 1M'},{h:60,c:5,label:'1H → 5M'},{h:240,c:15,label:'4H → 15M'}];
const bucket=(ms,min)=>Math.floor(ms/60000/min)*min;
function trade(s,p,ms){let m=store.get(s);if(!m)store.set(s,m=new Map());let k=bucket(ms,1),x=m.get(k)||{time:k,open:p,high:p,low:p,close:p};x.high=Math.max(x.high,p);x.low=Math.min(x.low,p);x.close=p;m.set(k,x);if(m.size>20000)m.delete(m.keys().next().value)}
function agg(s,min,end){let m=store.get(s);if(!m)return null;let a=[];for(let i=end-min+1;i<=end;i++){let x=m.get(i);if(x)a.push(x)}if(!a.length)return null;return{time:bucket(end,min),open:a[0].open,high:Math.max(...a.map(x=>x.high)),low:Math.min(...a.map(x=>x.low)),close:a[a.length-1].close}}
function fake(s,now){let out=[];for(let q of CFG){let cc=agg(s,q.c,now-1);if(!cc)continue;let ref=agg(s,q.h,cc.time-1);if(!ref)continue;if(cc.high>ref.high&&cc.close<ref.high)out.push({symbol:s,type:'FAKEOUT',direction:'BEARISH',timeframe:q.label,levelType:'HIGH',level:ref.high,confirmTime:(cc.time+q.c)*60000});if(cc.low<ref.low&&cc.close>ref.low)out.push({symbol:s,type:'FAKEOUT',direction:'BULLISH',timeframe:q.label,levelType:'LOW',level:ref.low,confirmTime:(cc.time+q.c)*60000})}return out}
function daily(s,now){let d=1440,cur=bucket(now,d),p=agg(s,d,cur-1),b=agg(s,d,cur-d-1),out=[];if(!p||!b)return out;if(p.high>b.high&&p.close<b.high)out.push({symbol:s,type:'DAILY_SWEEP',direction:'BEARISH',levelType:'HIGH',level:b.high,confirmTime:(p.time+d)*60000});if(p.low<b.low&&p.close>b.low)out.push({symbol:s,type:'DAILY_SWEEP',direction:'BULLISH',levelType:'LOW',level:b.low,confirmTime:(p.time+d)*60000});return out}
async function pairs(){try{let r=await axios.get('https://public.coindcx.com/market_data/v3/active_instruments/futures',{timeout:15000}),a=Array.isArray(r.data)?r.data:(r.data.instruments||[]);let p=a.map(x=>x.pair||x.symbol||x.market).filter(x=>/USDT$|INR$/i.test(x));if(!p.some(x=>x.toUpperCase()==='XAUUSDT'))p.push('XAUUSDT');return [...new Set(p)]}catch(e){return ['XAUUSDT']}}
async function start(){let ps=await pairs(),ws=clientIO('https://stream.coindcx.com',{transports:['websocket']});ws.on('connect',()=>ps.forEach(p=>ws.emit('join',{channelName:p+'@trades-futures'})));ws.on('newTrade',m=>{let s=m.pair||m.symbol||m.market,p=Number(m.price||m.p||m.rate);if(s&&Number.isFinite(p)){trade(s,p,Date.now());io.emit('tick',{symbol:s,price:p,time:Date.now()})}})}
setInterval(()=>{let n=Math.floor(Date.now()/60000);for(let s of store.keys()){let f=fake(s,n),d=daily(s,n);if(f.length||d.length)io.emit('signals',{fakeouts:f,sweeps:d})}},5000);app.get('/health',(_,r)=>r.json({ok:true}));server.listen(process.env.PORT||3000,start);
